"""empty message

Revision ID: 6aaac88a4107
Revises: 747256bd90bc
Create Date: 2023-11-07 20:43:21.918213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aaac88a4107'
down_revision = '747256bd90bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('date_published', sa.DateTime(), nullable=True))
    op.add_column('news', sa.Column('content', sa.String(), nullable=True))
    op.add_column('news', sa.Column('publishing_organization', sa.String(), nullable=True))
    op.drop_column('news', 'date')
    op.drop_column('news', 'article')
    op.drop_column('news', 'publishing_org')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('publishing_org', sa.VARCHAR(), nullable=True))
    op.add_column('news', sa.Column('article', sa.VARCHAR(), nullable=True))
    op.add_column('news', sa.Column('date', sa.DATETIME(), nullable=True))
    op.drop_column('news', 'publishing_organization')
    op.drop_column('news', 'content')
    op.drop_column('news', 'date_published')
    # ### end Alembic commands ###
