"""empty message

Revision ID: 747256bd90bc
Revises: 
Create Date: 2023-11-07 19:54:44.774457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747256bd90bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('article_image', sa.String(), nullable=True),
    sa.Column('publishing_org', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], name=op.f('fk_news_favorite_id_favorites')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_news_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_table('users')
    op.drop_table('favorites')
    # ### end Alembic commands ###
